# Generated by Django 5.1.3 on 2024-11-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Profile_Pic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contact_no',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
